name: Cypress Verify PR (Windows)

on: push


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          #working-directory: /home/runner/work/t250715/t250715/
          working-directory: 
          install: false
          build: npm run build
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:3000' # URL to wait for