name: Cypress Verify PR (Windows)

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Yarn
        run: npm install -g yarn
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start