name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: node:22
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
        with:
          node-version: 22
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - run: npm ci
      - run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start