name: Example Tests
# This workflow tests examples from the examples directory of this repo.

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress tests
        uses: ./
        with:
          working-directory: t250715/t250715/
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'