name: Cypress Tests

on: push

jobs:
  start:
    # example with web application build,
    # server start and waiting for the server
    # to respond before running tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: client
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'