name: Cypress Verify PR (Windows)

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: /home/runner/work/t250715/t250715
          build: npm run build
          start: npm start
          browser: chrome