name: Front-end CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    cypress-run:
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - run: npm ci
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm start