name: Example Tests
# This workflow tests examples from the examples directory of this repo.

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./
          #build: npm run build
          start: npx cypress run