name: Cypress Verify PR (Windows)

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run e2e:ci
          start: npm start